sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t tripdubroot/deity .
  - docker run -it --rm tripdubroot/deity npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tripdubroot/deity;
    fi
